-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE POLICY "允许新用户插入自己的资料" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);