-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 创建点赞表
CREATE TABLE IF NOT EXISTS public.likes (
  id SERIAL PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  merchant_id INTEGER NOT NULL REFERENCES public.merchants(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(user_id, merchant_id)
);

-- 创建评论表
CREATE TABLE IF NOT EXISTS public.reviews (
  id SERIAL PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  merchant_id INTEGER NOT NULL REFERENCES public.merchants(id) ON DELETE CASCADE,
  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  content TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 启用 RLS
ALTER TABLE public.likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- 点赞表策略
CREATE POLICY "所有人可查看点赞数" ON public.likes FOR SELECT USING (true);
CREATE POLICY "认证用户可点赞" ON public.likes FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "用户可取消自己的点赞" ON public.likes FOR DELETE USING (auth.uid() = user_id);

-- 评论表策略
CREATE POLICY "所有人可查看评论" ON public.reviews FOR SELECT USING (true);
CREATE POLICY "认证用户可发表评论" ON public.reviews FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "用户可更新自己的评论" ON public.reviews FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "用户可删除自己的评论" ON public.reviews FOR DELETE USING (auth.uid() = user_id);