-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 创建用户角色枚举
CREATE TYPE public.app_role AS ENUM ('user', 'merchant', 'admin');

-- 创建会员等级表
CREATE TABLE public.member_levels (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  icon VARCHAR(10),
  color VARCHAR(20),
  min_views INTEGER DEFAULT 0,
  privileges TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 创建用户资料表
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username VARCHAR(50) UNIQUE,
  phone VARCHAR(20),
  avatar_url TEXT,
  role app_role DEFAULT 'user',
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 创建商家信息表
CREATE TABLE public.merchants (
  id SERIAL PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  shop_name VARCHAR(100) NOT NULL,
  address TEXT NOT NULL,
  phone VARCHAR(20) NOT NULL,
  description TEXT,
  cover_image TEXT,
  images TEXT[],
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  member_level_id INTEGER REFERENCES public.member_levels(id),
  views INTEGER DEFAULT 0,
  rating DECIMAL(3, 2) DEFAULT 0.00,
  sales_count INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 创建分类表
CREATE TABLE public.categories (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  icon VARCHAR(10),
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 创建菜品/服务表
CREATE TABLE public.menus (
  id SERIAL PRIMARY KEY,
  merchant_id INTEGER REFERENCES public.merchants(id) ON DELETE CASCADE,
  category_id INTEGER REFERENCES public.categories(id),
  name VARCHAR(100) NOT NULL,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL,
  image TEXT,
  is_available BOOLEAN DEFAULT true,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 创建角色检查函数（必须在RLS策略之前创建）
CREATE OR REPLACE FUNCTION public.has_role(_user_id UUID, _role app_role)
RETURNS BOOLEAN
LANGUAGE SQL STABLE
SECURITY DEFINER SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = _user_id AND role = _role
  )
$$;

-- 启用行级安全
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.merchants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menus ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.member_levels ENABLE ROW LEVEL SECURITY;

-- 创建 profiles 的 RLS 策略
CREATE POLICY "用户可以查看自己的资料" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "用户可以更新自己的资料" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "管理员可以查看所有用户资料" ON public.profiles FOR SELECT USING (public.has_role(auth.uid(), 'admin'));

-- 创建 merchants 的 RLS 策略
CREATE POLICY "所有人可查看已通过的商家" ON public.merchants FOR SELECT USING (status = 'approved' OR auth.uid() = user_id OR public.has_role(auth.uid(), 'admin'));
CREATE POLICY "认证用户可创建商家申请" ON public.merchants FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "商家可更新自己的店铺信息" ON public.merchants FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "管理员可管理所有商家" ON public.merchants FOR ALL USING (public.has_role(auth.uid(), 'admin'));

-- 创建 categories 的 RLS 策略
CREATE POLICY "所有人可查看分类" ON public.categories FOR SELECT USING (true);
CREATE POLICY "管理员可管理分类" ON public.categories FOR ALL USING (public.has_role(auth.uid(), 'admin'));

-- 创建 menus 的 RLS 策略
CREATE POLICY "所有人可查看可用菜品" ON public.menus FOR SELECT USING (is_available = true OR EXISTS (SELECT 1 FROM public.merchants WHERE id = menus.merchant_id AND user_id = auth.uid()) OR public.has_role(auth.uid(), 'admin'));
CREATE POLICY "商家可管理自己的菜品" ON public.menus FOR ALL USING (EXISTS (SELECT 1 FROM public.merchants WHERE id = menus.merchant_id AND user_id = auth.uid()));
CREATE POLICY "管理员可管理所有菜品" ON public.menus FOR ALL USING (public.has_role(auth.uid(), 'admin'));

-- 创建 member_levels 的 RLS 策略
CREATE POLICY "所有人可查看会员等级" ON public.member_levels FOR SELECT USING (true);
CREATE POLICY "管理员可管理会员等级" ON public.member_levels FOR ALL USING (public.has_role(auth.uid(), 'admin'));

-- 插入默认会员等级
INSERT INTO public.member_levels (name, icon, color, min_views, privileges) VALUES
('普通商家', '🏪', '#94a3b8', 0, '基础展示'),
('银牌商家', '🥈', '#64748b', 1000, '优先展示,专属标识'),
('金牌商家', '🥇', '#fbbf24', 5000, '首页推荐,专属客服'),
('钻石商家', '💎', '#3b82f6', 10000, '顶级曝光,营销支持');

-- 插入默认分类
INSERT INTO public.categories (name, icon, sort_order) VALUES
('餐饮美食', '🍜', 1),
('洗浴汗蒸', '🛁', 2),
('汽车服务', '🚗', 3),
('生鲜果蔬', '🥬', 4),
('休闲娱乐', '🎮', 5),
('美容美发', '💇', 6),
('教育培训', '📚', 7),
('生活服务', '🔧', 8);

-- 创建浏览量自动升级触发器函数
CREATE OR REPLACE FUNCTION public.check_merchant_level_upgrade()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
  new_level_id INTEGER;
BEGIN
  -- 根据浏览量找到合适的会员等级
  SELECT id INTO new_level_id
  FROM public.member_levels
  WHERE min_views <= NEW.views
  ORDER BY min_views DESC
  LIMIT 1;
  
  -- 如果找到更高等级且与当前不同，则升级
  IF new_level_id IS NOT NULL AND new_level_id != NEW.member_level_id THEN
    NEW.member_level_id = new_level_id;
  END IF;
  
  RETURN NEW;
END;
$$;

-- 创建触发器
CREATE TRIGGER trigger_check_merchant_level
  BEFORE UPDATE OF views ON public.merchants
  FOR EACH ROW
  EXECUTE FUNCTION public.check_merchant_level_upgrade();