-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

DROP POLICY IF EXISTS "允许用户插入自己的资料" ON public.profiles;
DROP POLICY IF EXISTS "用户可以查看自己的资料" ON public.profiles;
DROP POLICY IF EXISTS "用户可以更新自己的资料" ON public.profiles;
DROP POLICY IF EXISTS "管理员可以查看所有用户资料" ON public.profiles;

CREATE POLICY "用户可以查看自己的资料" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "用户可以更新自己的资料" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "管理员可以查看所有用户资料" ON public.profiles FOR SELECT USING (public.has_role(auth.uid(), 'admin'));