-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 创建收藏表
CREATE TABLE IF NOT EXISTS public.favorites (
  id SERIAL PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  merchant_id INTEGER NOT NULL REFERENCES public.merchants(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(user_id, merchant_id)
);

-- 创建订单表
CREATE TABLE IF NOT EXISTS public.orders (
  id SERIAL PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  merchant_id INTEGER NOT NULL REFERENCES public.merchants(id) ON DELETE CASCADE,
  total_amount DECIMAL(10,2) NOT NULL,
  status VARCHAR(50) DEFAULT 'pending',
  address TEXT NOT NULL,
  phone VARCHAR(20) NOT NULL,
  note TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 创建订单详情表
CREATE TABLE IF NOT EXISTS public.order_items (
  id SERIAL PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  menu_id INTEGER NOT NULL REFERENCES public.menus(id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 创建优惠券表
CREATE TABLE IF NOT EXISTS public.coupons (
  id SERIAL PRIMARY KEY,
  merchant_id INTEGER REFERENCES public.merchants(id) ON DELETE CASCADE,
  title VARCHAR(100) NOT NULL,
  description TEXT,
  discount_amount DECIMAL(10,2),
  min_amount DECIMAL(10,2) DEFAULT 0,
  valid_from TIMESTAMP DEFAULT NOW(),
  valid_until TIMESTAMP,
  total_quantity INTEGER DEFAULT 100,
  used_quantity INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 创建用户优惠券表
CREATE TABLE IF NOT EXISTS public.user_coupons (
  id SERIAL PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  coupon_id INTEGER NOT NULL REFERENCES public.coupons(id) ON DELETE CASCADE,
  is_used BOOLEAN DEFAULT false,
  used_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(user_id, coupon_id)
);

-- 创建消息通知表
CREATE TABLE IF NOT EXISTS public.notifications (
  id SERIAL PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title VARCHAR(200) NOT NULL,
  content TEXT,
  type VARCHAR(50) DEFAULT 'system',
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 启用 RLS
ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- 收藏表策略
CREATE POLICY "用户可查看自己的收藏" ON public.favorites FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "用户可添加收藏" ON public.favorites FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "用户可取消收藏" ON public.favorites FOR DELETE USING (auth.uid() = user_id);

-- 订单表策略
CREATE POLICY "用户可查看自己的订单" ON public.orders FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "商家可查看关联订单" ON public.orders FOR SELECT USING (EXISTS (SELECT 1 FROM public.merchants WHERE id = merchant_id AND user_id = auth.uid()));
CREATE POLICY "用户可创建订单" ON public.orders FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "用户可更新自己的订单" ON public.orders FOR UPDATE USING (auth.uid() = user_id);

-- 订单详情策略
CREATE POLICY "用户可查看自己的订单详情" ON public.order_items FOR SELECT USING (EXISTS (SELECT 1 FROM public.orders WHERE id = order_id AND user_id = auth.uid()));
CREATE POLICY "商家可查看关联订单详情" ON public.order_items FOR SELECT USING (EXISTS (SELECT 1 FROM public.orders o JOIN public.merchants m ON o.merchant_id = m.id WHERE o.id = order_id AND m.user_id = auth.uid()));

-- 优惠券策略
CREATE POLICY "所有人可查看优惠券" ON public.coupons FOR SELECT USING (true);
CREATE POLICY "商家可管理自己的优惠券" ON public.coupons FOR ALL USING (EXISTS (SELECT 1 FROM public.merchants WHERE id = merchant_id AND user_id = auth.uid()));

-- 用户优惠券策略
CREATE POLICY "用户可查看自己的优惠券" ON public.user_coupons FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "用户可领取优惠券" ON public.user_coupons FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 通知策略
CREATE POLICY "用户可查看自己的通知" ON public.notifications FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "系统可发送通知" ON public.notifications FOR INSERT WITH CHECK (true);
CREATE POLICY "用户可标记通知已读" ON public.notifications FOR UPDATE USING (auth.uid() = user_id);