-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 删除旧的 SELECT 策略
DROP POLICY IF EXISTS "所有人可查看已通过的商家" ON public.merchants;

-- 创建新的 SELECT 策略：允许商家查看自己的店铺，管理员查看所有，公众只看已通过
CREATE POLICY "商家可查看自己的店铺信息" ON public.merchants
FOR SELECT USING (
  auth.uid() = user_id OR 
  has_role(auth.uid(), 'admin'::app_role) OR 
  status = 'approved'
);