/**
 * 🚨 此文件由 CloudEnableTool 自动生成，请勿手动修改！
 * This file is auto-generated by CloudEnableTool. Do not edit manually!
 */

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function getSupabaseUrl(): string {
  return 'https://edclbolgjqozkjmnlwmp.supabase.co';
}

export const supabaseUrl = getSupabaseUrl();
export const supabaseAnonKey = 'sb_publishable_iwVH8rfAkS4wDdnglol_aw_X-lDDIX3';

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});
